name: validate to prod
on:
  push:
    branches:
      - dev
jobs:
  validate-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: >
          wget
          https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

          mkdir ~/sfdx

          tar xJf sfdx-linux-x64.tar.xz -C ~/sf --strip-components 1

          echo "$HOME/sfdx/bin" >> $GITHUB_PATH

          ~/sfdx/bin/sf version
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.PROD_URL}} > ./PROD_URL.txt
      - name: Authenticate to target Org
        run: sf org login sfdx-url --sfdx-url-file ./PROD_URL.txt --set-default --alias myOrg
      - name: Deployment - run all tests
        run: >
          sf project deploy start --sourcepath "force-app" --json
